# Generated by Django 3.0.6 on 2020-05-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
